* Working with CSV data

* Due: Wed 12/14 7:00am

* Overview and general instructions

For this project you will have to find one or more interesting data
sources. You can search interesting data but here are a few starting
points:

- NYC Open data: https://opendata.cityofnewyork.us/
- Sports sites like https://www.baseball-reference.com/
- Various web sites with links to data sets:
  - https://corgis-edu.github.io/corgis/csv/
  - https://www.dataquest.io/blog/free-datasets-for-projects/
  - https://www.kaggle.com/rtatman/fun-beginner-friendly-datasets 
  - https://www.kaggle.com
  - https://rs.io/100-interesting-data-sets-for-statistics/
  - https://domohelp.domo.com/hc/en-us/articles/360043931814-Fun-Sample-DataSets
  - https://www.dataquest.io/blog/free-datasets-for-projects/


You will write a Python program that does some interesting analysis on
one or more data sets.

For example, one of the data sets in one of the above sits has
Jeopardy questions. You could do a text analysis (Bag of Words) on
Jeopardy questions. Another example would be taking pieces of 311 data and
correlating them with each other or with some other data set. Like
seeing if there's a correlation between trash complaints and noise
complaints with respect to zip code or some other type of complaint
with crime data.

You should use the Python csv module to read in the data. You can look
at the sample code we wrote but there are also lots of tutorials
online.

If you want to show your analysis with plots and/or graphs, look up
the Python mathplotlib library.


    
* Assignment specific instructions:

Your program should go in a folder named *data* and your program file
should be named *data.py*.




** Assignment notes:

For this assignment, you are to decide what functions to write, what
to name them and how to structure your program.

You can work solo or with a partner. If you work with a partner it has
to be a new partner (not the same partner you worked with on a
previous assignment).

As with past assignments, you should note any partner you work with in
a comment at the top of the program file. You should also list any
extras you complete in a similar comment as well as any citations.

*Important:* Make sure to upload the required datasets to your GitHub
repo.

** Grading

For a B grade, you just have to downoad a single data source, read it
in using the Python CSV module and perform some basic analysis on the
data (average of some field, extract some meaningful subset etc.) and
report on the results.


|                          | Working alone | Working with a partner |
|--------------------------+---------------+------------------------|
| Base project (see below) | B             | C                      |
| One extra                | A             | B                      |
| Two extras               | A             | A                      |



** Extras

If you work with a partner you must implement at least one extras for
the base grade. You can also suggest extras by proposing them on
zulip.

- Use Matplotlib or another Python graphing/plotting library to
  visualize part or all of your analysis.
- Use multiple aspects of a single data source in your analysis
- Use more than one data source and have your analysis
  compare,contrast, or correlate them.
- Do an analysis that includes the language processing work (Bag of
  Words type analysis for example).
  
Feel free to suggest other extras on zulip



  
